User can edit family member
nafiesl/silsilah pull request #89
Opened 2022-10-28 05:06 UTC by xtrsyz

2022-10-28 10:10 UTC, nafiesl commented
Hello @xtrsyz, would you mind adding unit tests regarding these changes?
You may refer to the testing classes in this directory:

https://github.com/nafiesl/silsilah/tree/master/tests/Unit/Policies

I will review this PR after the testing has been added.

Thanks.

2022-10-28 13:22 UTC, xtrsyz commented
sorry I don't understand how to add it.
and I don't have time to learn it again.
thanks.

2022-10-28 14:21 UTC, nafiesl commented
Hi @xtrsyz, this project has been covered by automated testing. Every feature that has impacts on the database changes (create, edit or delete) must be covered by testing.

I can understand if you don't have time to write the tests. So I will leave this PR open until I or someone else can write tests for these changes.

Thanks for your idea and contribution. I appreciate your time working on this PR.

### Current Progress

1. Write logic that allows users to edit their own family members (new authorization)

### Next TODO

1. Write tests on [policy objects](https://github.com/nafiesl/silsilah/tree/master/tests/Unit/Policies) covering the user authorizations to edit family members.

2023-07-02 18:18 UTC, xtrsyz commented
Hi @nafiesl, i have create test unit for this.
Thanks.

2023-07-31 16:05 UTC, nafiesl requested changes
Terima kasih mas @xtrsyz sudah kasih testingnya. Saya ada beberapa masukan terkait kodenya mas.

Kemudian ini ada kontribusi yang bagus juga dari mas @azharlihan, dimana testingnya dipisah2 sesuai konteks nya (siapa boleh meng-edit siapa).
https://github.com/nafiesl/silsilah/pull/105/files

2023-07-31 16:05 UTC, nafiesl commented on app/Policies/UserPolicy.php
>          return $editableUser->id == $user->id || $editableUser->manager_id == $user->id || is_system_admin($user);
Kalau dibuat gini lebih readable ngga ya mas @xtrsyz?
```suggestion
        return $editableUser->id == $user->id
        || $editableUser->manager_id == $user->id
        || is_system_admin($user)
        || $editableUser->id == $user->father_id
        || $editableUser->id == $user->mother_id
        || $editableUser->father_id == $user->id
        || $editableUser->mother_id == $user->id
        || $user->husbands->pluck('id')->contains($editableUser->id)
        || $user->wifes->pluck('id')->contains($editableUser->id)
        ;
```

2023-08-01 03:17 UTC, nafiesl commented on tests/Unit/Policies/UserPolicyTest.php
> +        $couple = factory(Couple::class)->create();
mas @xtrsyz class `Couple` ini belum diimport.

![screen_2023-08-01_008](https://github.com/nafiesl/silsilah/assets/8721551/355cdbdc-3d09-429f-904f-d4d6125fee46)

2023-08-01 06:57 UTC, xtrsyz commented on tests/Unit/Policies/UserPolicyTest.php
> +        $couple = factory(Couple::class)->create();
ok terimakasih, menambah ilmu baru.
![image](https://github.com/nafiesl/silsilah/assets/4731553/7e5d9c75-f780-449b-a6e7-d5f414f780eb)

2023-08-01 10:02 UTC, nafiesl approved these changes
Dah sip, thanks mas @xtrsyz

2023-08-01 10:02 UTC, merged